package vista;

import controlador.FacturaController;
import controlador.ReparacionController;
import javax.swing.DefaultComboBoxModel;
import modelo.Factura;
import modelo.Factura.MetodoPago;
import modelo.Reparacion;
import util.DialogUtil;
import util.ResultadoOperacion;

/**
 * Diálogo para crear o editar facturas.
 *
 * @author Mendoza Sebastian
 */
public class FacturaDialog extends javax.swing.JDialog {

    private final FacturaController controller;
    private final ReparacionController reparacionController;
    private Factura factura = null;

    /**
     * Creates new form FacturaDialog
     *
     * @param parent
     * @param modal
     * @param factura
     */
    public FacturaDialog(java.awt.Frame parent, boolean modal, Factura factura) {
        super(parent, modal);
        initComponents();

        controller = new FacturaController();
        reparacionController = new ReparacionController();

        this.factura = factura;

        cargarReparaciones();
        cargarMetodos();

        if (factura != null) {
            lblTitulo.setText("Editar Factura");
            btnGuardar.setText("Actualizar");
            cargarDatos();
        } else {
            lblTitulo.setText("Nueva Factura");
            btnGuardar.setText("Guardar");
        }
    }

    /**
     * Carga reparaciones finalizadas
     */
    private void cargarReparaciones() {
        DefaultComboBoxModel<Reparacion> model = new DefaultComboBoxModel<>();

        for (Reparacion r : reparacionController.listar()) {
            if (r.getEstado() == Reparacion.Estado.FINALIZADO) {
                model.addElement(r);
            }
        }

        cbxReparacion.setModel(model);
    }

    /**
     * Carga métodos de pago
     */
    private void cargarMetodos() {
        cbxMetodo.setModel(new DefaultComboBoxModel<>(MetodoPago.values()));
    }

    /**
     * Carga los datos de la factura en el formulario (modo edición).
     */
    private void cargarDatos() {
        cbxReparacion.setSelectedItem(factura.getReparacion());
        txtCosto.setText(String.valueOf(factura.getCostoTotal()));
        txtaObservaciones.setText(factura.getObservaciones());
        cbxMetodo.setSelectedItem(factura.getMetodoPago());
    }

    /**
     * Valida y guarda los datos del formulario. Si la factura es null, realiza
     * un INSERT. Si existe, realiza un UPDATE.
     */
    private void guardarDatos() {
        try {
            Factura f = new Factura();

            if (factura != null) {
                f.setId(factura.getId());
            }

            f.setReparacion((Reparacion) cbxReparacion.getSelectedItem());
            f.setCostoTotal(Double.parseDouble(txtCosto.getText().trim()));
            f.setObservaciones(txtaObservaciones.getText().trim());
            f.setMetodoPago((MetodoPago) cbxMetodo.getSelectedItem());

            ResultadoOperacion resultado = (factura == null)
                    ? controller.guardarFactura(f)
                    : controller.actualizarFactura(f);

            if (!resultado.isExito()) {
                DialogUtil.mostrarMensajeAdvertencia(this, resultado.getMensaje());
                return;
            }

            DialogUtil.mostrarMensajeInformacion(this, resultado.getMensaje());
            dispose();

        } catch (NumberFormatException e) {
            DialogUtil.mostrarMensajeAdvertencia(this, "El costo debe ser numérico");
        } catch (Exception ex) {
            DialogUtil.mostrarMensajeError(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblReparacion = new javax.swing.JLabel();
        cbxReparacion = new javax.swing.JComboBox<Reparacion>();
        lblObservaciones = new javax.swing.JLabel();
        scrObservaciones = new javax.swing.JScrollPane();
        txtaObservaciones = new javax.swing.JTextArea();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblMetodo = new javax.swing.JLabel();
        cbxMetodo = new javax.swing.JComboBox<MetodoPago>();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(204, 255, 204));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nueva Factura");

        lblReparacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReparacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReparacion.setText("Reparación *:");

        lblObservaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblObservaciones.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservaciones.setText("Observaciones *:");

        txtaObservaciones.setColumns(20);
        txtaObservaciones.setLineWrap(true);
        txtaObservaciones.setRows(5);
        txtaObservaciones.setWrapStyleWord(true);
        scrObservaciones.setViewportView(txtaObservaciones);

        lblCosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCosto.setText("Costo *:");

        txtCosto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblMetodo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMetodo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMetodo.setText("Método De Pago *:");

        btnGuardar.setBackground(new java.awt.Color(0, 204, 102));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMetodo)
                            .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblObservaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblReparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                            .addComponent(lblCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxReparacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrObservaciones)
                            .addComponent(cbxMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCosto))
                        .addGap(30, 30, 30))))
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReparacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(scrObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCosto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMetodo)))
                    .addComponent(lblObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<MetodoPago> cbxMetodo;
    private javax.swing.JComboBox<Reparacion> cbxReparacion;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblReparacion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JScrollPane scrObservaciones;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextArea txtaObservaciones;
    // End of variables declaration//GEN-END:variables
}
