package vista;

import controlador.EquipoMovilController;
import controlador.RecepcionEntregaController;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import modelo.EquipoMovil;
import modelo.RecepcionEntrega;
import util.DialogUtil;
import util.ResultadoOperacion;
import util.Sesion;

/**
 * Diálogo para crear o editar recepciones.
 *
 * @author Baque Diego
 */
public class RecepcionEntregaDialog extends javax.swing.JDialog {

    private final RecepcionEntregaController controller;
    private final EquipoMovilController equipoController;
    private RecepcionEntrega recepcion = null;

    /**
     * Creates new form RecepcionEntregaDialog
     *
     * @param parent
     * @param modal
     * @param recepcion
     */
    public RecepcionEntregaDialog(java.awt.Frame parent, boolean modal, RecepcionEntrega recepcion) {
        super(parent, modal);
        initComponents();

        controller = new RecepcionEntregaController();
        equipoController = new EquipoMovilController();

        this.recepcion = recepcion;

        cargarEquipos();

        if (recepcion != null) {
            lblTitulo.setText("Editar Recepción");
            btnGuardar.setText("Actualizar");
            btnGuardar.setBackground(new Color(102, 102, 255));
            cargarDatos();
        } else {
            lblTitulo.setText("Nueva Recepción");
            btnGuardar.setText("Guardar");
            btnGuardar.setBackground(new Color(103, 201, 228));
        }
    }

    /**
     * Carga combo de equipos móviles
     */
    private void cargarEquipos() {
        DefaultComboBoxModel<EquipoMovil> model = new DefaultComboBoxModel<>();

        for (EquipoMovil e : equipoController.listarEquipos()) {
            model.addElement(e);
        }

        cbxEquipo.setModel(model);
    }

    /**
     * Carga los datos de la recepción en el formulario (modo edición).
     */
    private void cargarDatos() {
        cbxEquipo.setSelectedItem(recepcion.getEquipoMovil());
        txtaProblema.setText(recepcion.getProblemaReportado());
    }

    /**
     * Valida y guarda los datos del formulario. Si la recepción es null,
     * realiza un INSERT. Si existe, realiza un UPDATE.
     */
    private void guardarDatos() {
        try {
            RecepcionEntrega r = new RecepcionEntrega();

            if (recepcion != null) {
                r.setId(recepcion.getId());
            }

            r.setEquipoMovil((EquipoMovil) cbxEquipo.getSelectedItem());
            r.setProblemaReportado(txtaProblema.getText().trim());
            r.setUsuario(Sesion.getUsuarioActual());

            ResultadoOperacion resultado = (recepcion == null)
                    ? controller.guardarRecepcion(r)
                    : controller.actualizarRecepcion(r);

            if (!resultado.isExito()) {
                DialogUtil.mostrarMensajeAdvertencia(this, resultado.getMensaje());
                return;
            }

            DialogUtil.mostrarMensajeInformacion(this, resultado.getMensaje());
            dispose();

        } catch (Exception ex) {
            DialogUtil.mostrarMensajeError(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblProblema = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblEquipo = new javax.swing.JLabel();
        cbxEquipo = new javax.swing.JComboBox<EquipoMovil>();
        scrProblema = new javax.swing.JScrollPane();
        txtaProblema = new javax.swing.JTextArea();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nueva Recepción");

        lblProblema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProblema.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProblema.setText("Problema *:");

        btnGuardar.setBackground(new java.awt.Color(103, 201, 228));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblEquipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEquipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipo.setText("Equipo Móvil *:");

        txtaProblema.setColumns(20);
        txtaProblema.setLineWrap(true);
        txtaProblema.setRows(5);
        txtaProblema.setWrapStyleWord(true);
        scrProblema.setViewportView(txtaProblema);

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/favicon.png"))); // NOI18N

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlFormularioLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(imagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(cbxEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipo))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProblema)
                    .addComponent(scrProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnGuardar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<EquipoMovil> cbxEquipo;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblProblema;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JScrollPane scrProblema;
    private javax.swing.JTextArea txtaProblema;
    // End of variables declaration//GEN-END:variables
}
