package vista;

import controlador.EquipoMovilController;
import controlador.RecepcionEntregaController;
import javax.swing.DefaultComboBoxModel;
import modelo.EquipoMovil;
import modelo.RecepcionEntrega;
import util.DialogUtil;
import util.ResultadoOperacion;
import util.Sesion;

/**
 * Diálogo para crear o editar recepciones.
 *
 * @author Baque Diego
 */
public class RecepcionEntregaDialog extends javax.swing.JDialog {

    private final RecepcionEntregaController controller;
    private final EquipoMovilController equipoController;
    private RecepcionEntrega recepcion = null;

    /**
     * Creates new form RecepcionEntregaDialog
     *
     * @param parent
     * @param modal
     * @param recepcion
     */
    public RecepcionEntregaDialog(java.awt.Frame parent, boolean modal, RecepcionEntrega recepcion) {
        super(parent, modal);
        initComponents();

        controller = new RecepcionEntregaController();
        equipoController = new EquipoMovilController();

        this.recepcion = recepcion;

        cargarEquipos();
        cargarEstados();

        if (recepcion != null) {
            lblTitulo.setText("Editar Recepción");
            btnGuardar.setText("Actualizar");
            cargarDatos();
        } else {
            lblTitulo.setText("Nueva Recepción");
            btnGuardar.setText("Guardar");
        }
    }

    /**
     * Carga combo de equipos móviles
     */
    private void cargarEquipos() {
        DefaultComboBoxModel<EquipoMovil> model = new DefaultComboBoxModel<>();

        for (EquipoMovil e : equipoController.listarEquipos()) {
            model.addElement(e);
        }

        cbxEquipo.setModel(model);
    }

    /**
     * Carga combo de estados
     */
    private void cargarEstados() {
        cbxEstado.setModel(new DefaultComboBoxModel<>(RecepcionEntrega.Estado.values()));
    }

    /**
     * Carga los datos de la recepción en el formulario (modo edición).
     */
    private void cargarDatos() {
        cbxEquipo.setSelectedItem(recepcion.getEquipoMovil());
        txtaProblema.setText(recepcion.getProblemaReportado());
        cbxEstado.setSelectedItem(recepcion.getEstado());
    }

    /**
     * Valida y guarda los datos del formulario. Si la recepción es null,
     * realiza un INSERT. Si existe, realiza un UPDATE.
     */
    private void guardarDatos() {
        try {
            RecepcionEntrega r = new RecepcionEntrega();

            if (recepcion != null) {
                r.setId(recepcion.getId());
            }

            r.setEquipoMovil((EquipoMovil) cbxEquipo.getSelectedItem());
            r.setProblemaReportado(txtaProblema.getText().trim());
            r.setEstado((RecepcionEntrega.Estado) cbxEstado.getSelectedItem());
            r.setUsuario(Sesion.getUsuarioActual());

            ResultadoOperacion resultado = (recepcion == null)
                    ? controller.guardarRecepcion(r)
                    : controller.actualizarRecepcion(r);

            if (!resultado.isExito()) {
                DialogUtil.mostrarMensajeAdvertencia(this, resultado.getMensaje());
                return;
            }

            DialogUtil.mostrarMensajeInformacion(this, resultado.getMensaje());
            dispose();

        } catch (Exception ex) {
            DialogUtil.mostrarMensajeError(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblProblema = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblEquipo = new javax.swing.JLabel();
        cbxEquipo = new javax.swing.JComboBox<EquipoMovil>();
        scrProblema = new javax.swing.JScrollPane();
        txtaProblema = new javax.swing.JTextArea();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<RecepcionEntrega.Estado>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(204, 153, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nueva Recepción");

        lblProblema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProblema.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProblema.setText("Problema *:");

        btnGuardar.setBackground(new java.awt.Color(153, 51, 255));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblEquipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEquipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEquipo.setText("Equipo Móvil *:");

        txtaProblema.setColumns(20);
        txtaProblema.setLineWrap(true);
        txtaProblema.setRows(5);
        txtaProblema.setWrapStyleWord(true);
        scrProblema.setViewportView(txtaProblema);

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado *:");

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEquipo))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProblema)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(scrProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<EquipoMovil> cbxEquipo;
    private javax.swing.JComboBox<RecepcionEntrega.Estado> cbxEstado;
    private javax.swing.JLabel lblEquipo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblProblema;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JScrollPane scrProblema;
    private javax.swing.JTextArea txtaProblema;
    // End of variables declaration//GEN-END:variables
}
