package vista;

import controlador.UsuarioController;
import modelo.Usuario;
import util.DialogUtil;
import util.ResultadoOperacion;

/**
 * Diálogo para reiniciar contraseñas de usuarios.
 *
 * @author Mendoza Sebastian
 */
public class ReiniciarContrasenaDialog extends javax.swing.JDialog {

    private final UsuarioController controlador = new UsuarioController();
    private Usuario usuario = null;

    /**
     * Creates new form ReiniciarContrasenaDialog
     *
     * @param parent
     * @param modal
     * @param usuario
     */
    public ReiniciarContrasenaDialog(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        initComponents();

        this.usuario = usuario;
    }

    /**
     * Valida y asigna la nueva contraseña.
     */
    private void guardarDatos() {
        try {
            String pass1 = new String(txtNueva.getPassword()).trim();
            String pass2 = new String(txtConfirmar.getPassword()).trim();

            if (pass1.isEmpty() || pass2.isEmpty()) {
                DialogUtil.mostrarMensajeAdvertencia(this, "Ingrese la nueva contraseña");
                return;
            }

            if (!pass1.equals(pass2)) {
                DialogUtil.mostrarMensajeError(this, "Las contraseñas no coinciden");
                return;
            }

            if (pass1.length() < 4) {
                DialogUtil.mostrarMensajeAdvertencia(this, "La contraseña debe tener al menos 4 caracteres");
                return;
            }

            usuario.setContrasena(pass1);

            ResultadoOperacion resultado = controlador.actualizarUsuario(usuario);

            if (!resultado.isExito()) {
                DialogUtil.mostrarMensajeError(this, resultado.getMensaje());
                return;
            }

            DialogUtil.mostrarMensajeInformacion(
                    this,
                    "Contraseña reiniciada correctamente\nNueva contraseña: " + pass1
            );

            dispose();

        } catch (Exception e) {
            DialogUtil.mostrarMensajeError(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNueva = new javax.swing.JLabel();
        txtNueva = new javax.swing.JPasswordField();
        lblConfirmar = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Reiniciando Contraseña");

        lblNueva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNueva.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNueva.setText("Nueva Contraseña *:");

        lblConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConfirmar.setText("Confirmar Contraseña *:");

        btnGuardar.setBackground(new java.awt.Color(20, 184, 166));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblTitulo))
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlFormularioLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblNueva)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormularioLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(lblConfirmar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNueva)
                    .addComponent(txtNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmar)
                    .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblNueva;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtNueva;
    // End of variables declaration//GEN-END:variables
}
