package vista;

import controlador.ReparacionController;
import controlador.RecepcionEntregaController;
import javax.swing.DefaultComboBoxModel;
import modelo.Reparacion;
import modelo.RecepcionEntrega;
import util.DialogUtil;
import util.ResultadoOperacion;
import util.Sesion;

/**
 * Diálogo para crear o editar reparaciones.
 *
 * @author Pluas Kevin
 */
public class ReparacionDialog extends javax.swing.JDialog {

    private final ReparacionController controller;
    private final RecepcionEntregaController recepcionController;
    private Reparacion reparacion = null;

    /**
     * Creates new form ReparacionDialog
     *
     * @param parent
     * @param modal
     * @param reparacion
     */
    public ReparacionDialog(java.awt.Frame parent, boolean modal, Reparacion reparacion) {
        super(parent, modal);
        initComponents();

        controller = new ReparacionController();
        recepcionController = new RecepcionEntregaController();
        this.reparacion = reparacion;

        cargarRecepciones();
        cargarEstados();

        if (reparacion != null) {
            lblTitulo.setText("Editar Reparación");
            btnGuardar.setText("Actualizar");
            cargarDatos();
        } else {
            lblTitulo.setText("Nueva Reparación");
            btnGuardar.setText("Guardar");
        }
    }

    /**
     * Carga combo de recepciones
     */
    private void cargarRecepciones() {
        DefaultComboBoxModel<RecepcionEntrega> model = new DefaultComboBoxModel<>();

        for (RecepcionEntrega r : recepcionController.listarRecepciones()) {
            if (r.getEstado() == RecepcionEntrega.Estado.RECIBIDO) {
                model.addElement(r);
            }
        }

        cbxRecepcion.setModel(model);
    }

    /**
     * Carga combo de estados
     */
    private void cargarEstados() {
        cbxEstado.setModel(new DefaultComboBoxModel<>(Reparacion.Estado.values()));
    }

    /**
     * Carga los datos de la reparación en el formulario (modo edición).
     */
    private void cargarDatos() {
        cbxRecepcion.setSelectedItem(reparacion.getRecepcion());
        txtaDiagnostico.setText(reparacion.getDiagnostico());
        txtaSolucion.setText(reparacion.getSolucion());
        txtaPiezas.setText(reparacion.getPiezasUsadas());
        txtCosto.setText(String.valueOf(reparacion.getCostoRepuestos()));
        cbxEstado.setSelectedItem(reparacion.getEstado());
    }

    /**
     * Valida y guarda los datos del formulario. Si la reparación es null,
     * realiza un INSERT. Si existe, realiza un UPDATE.
     */
    private void guardarDatos() {
        try {
            Reparacion r = new Reparacion();

            if (reparacion != null) {
                r.setId(reparacion.getId());
            }

            r.setRecepcion((RecepcionEntrega) cbxRecepcion.getSelectedItem());
            r.setDiagnostico(txtaDiagnostico.getText().trim());
            r.setSolucion(txtaSolucion.getText().trim());
            r.setPiezasUsadas(txtaPiezas.getText().trim());
            r.setEstado((Reparacion.Estado) cbxEstado.getSelectedItem());
            r.setUsuario(Sesion.getUsuarioActual());

            try {
                r.setCostoRepuestos(Double.parseDouble(txtCosto.getText().trim()));
            } catch (NumberFormatException e) {
                DialogUtil.mostrarMensajeAdvertencia(this, "El costo debe ser numérico");
                txtCosto.requestFocus();
                return;
            }

            ResultadoOperacion resultado;

            if (reparacion == null) {
                resultado = controller.guardar(r);
            } else {
                resultado = controller.actualizar(r);
            }

            if (!resultado.isExito()) {
                DialogUtil.mostrarMensajeAdvertencia(this, resultado.getMensaje());
                return;
            }

            DialogUtil.mostrarMensajeInformacion(this, resultado.getMensaje());
            dispose();

        } catch (Exception ex) {
            DialogUtil.mostrarMensajeError(this, "Error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormulario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblRecepcion = new javax.swing.JLabel();
        cbxRecepcion = new javax.swing.JComboBox<RecepcionEntrega>();
        lblDiagnostico = new javax.swing.JLabel();
        scrDiagnostico = new javax.swing.JScrollPane();
        txtaDiagnostico = new javax.swing.JTextArea();
        lblSolucion = new javax.swing.JLabel();
        scrSolucion = new javax.swing.JScrollPane();
        txtaSolucion = new javax.swing.JTextArea();
        lblPiezas = new javax.swing.JLabel();
        scrPiezas = new javax.swing.JScrollPane();
        txtaPiezas = new javax.swing.JTextArea();
        lblCosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<Reparacion.Estado>();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlFormulario.setBackground(new java.awt.Color(255, 204, 204));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nueva Reparación");

        lblRecepcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRecepcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecepcion.setText("Recepcion *:");

        lblDiagnostico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDiagnostico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiagnostico.setText("Diagnóstico *:");

        txtaDiagnostico.setColumns(20);
        txtaDiagnostico.setLineWrap(true);
        txtaDiagnostico.setRows(5);
        txtaDiagnostico.setWrapStyleWord(true);
        scrDiagnostico.setViewportView(txtaDiagnostico);

        lblSolucion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSolucion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSolucion.setText("Solución *:");

        txtaSolucion.setColumns(20);
        txtaSolucion.setLineWrap(true);
        txtaSolucion.setRows(5);
        txtaSolucion.setWrapStyleWord(true);
        scrSolucion.setViewportView(txtaSolucion);

        lblPiezas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPiezas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPiezas.setText("Piezas Usadas *:");

        txtaPiezas.setColumns(20);
        txtaPiezas.setLineWrap(true);
        txtaPiezas.setRows(5);
        txtaPiezas.setWrapStyleWord(true);
        scrPiezas.setViewportView(txtaPiezas);

        lblCosto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCosto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCosto.setText("Costo *:");

        txtCosto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado *:");

        btnGuardar.setBackground(new java.awt.Color(255, 102, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRecepcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(lblDiagnostico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSolucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPiezas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrPiezas)
                            .addComponent(cbxRecepcion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrDiagnostico)
                            .addComponent(cbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrSolucion)
                            .addComponent(txtCosto))
                        .addGap(30, 30, 30))))
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecepcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(scrSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                        .addComponent(lblSolucion)
                        .addGap(37, 37, 37)))
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPiezas)
                    .addGroup(pnlFormularioLayout.createSequentialGroup()
                        .addComponent(scrPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCosto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Reparacion.Estado> cbxEstado;
    private javax.swing.JComboBox<RecepcionEntrega> cbxRecepcion;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblPiezas;
    private javax.swing.JLabel lblRecepcion;
    private javax.swing.JLabel lblSolucion;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JScrollPane scrDiagnostico;
    private javax.swing.JScrollPane scrPiezas;
    private javax.swing.JScrollPane scrSolucion;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextArea txtaDiagnostico;
    private javax.swing.JTextArea txtaPiezas;
    private javax.swing.JTextArea txtaSolucion;
    // End of variables declaration//GEN-END:variables
}
